### ISSUE TITLE
Error {:error, ""}

### ISSUE THREAD

**Issue by vovkats** [gutschilla/elixir-pdf-generator#39] opened 2018-03-27 08:42 UTC
@gutschilla I got empty error message. How to get more details about error?

**Comment by gutschilla** [comment] 2018-03-27 09:31
@vovkats What was the command that you issued. Please provide some context, thank you.

**Comment by siliconavengers** [comment] 2018-03-29 06:37
@gutschilla  me too. 

here is my context:

```
# Ubuntu server 16.04

# Installed wkhtmltopdf 

sudo apt-get update
sudo apt-get install xvfb libfontconfig wkhtmltopdf

# Run the remote_console from server

iex(sample@127.0.0.1)2> PdfGenerator.generate_binary("<p>Hello World</p>", filename: "sample.html")
{:error, ""}
```

**Comment by siliconavengers** [comment] 2018-03-29 07:27
ax, nvm. I figure out. Here is how to fix

```
# Uninstall wkhtmltopdf

sudo apt-get remove wkhtmltopdf # To remove just wkhtmltopdf package itself from Ubuntu 16.04 (Xenial Xerus) execute on terminal

sudo apt-get remove --auto-remove wkhtmltopdf # Or to remove the wkhtmltopdf package and any other dependant package which are no longer needed from Ubuntu Xenial.

# And then, install new one

cd ~
wget https://github.com/wkhtmltopdf/wkhtmltopdf/releases/download/0.12.3/wkhtmltox-0.12.3_linux-generic-amd64.tar.xz
tar vxf wkhtmltox-0.12.3_linux-generic-amd64.tar.xz 
cp wkhtmltox/bin/wk* /usr/local/bin/

# Now, it works

Interactive Elixir (1.6.1) - press Ctrl+C to exit (type h() ENTER for help)
iex(sample@127.0.0.1)1> PdfGenerator.generate_binary("<p>Hello World</p>", filename: "sample.html")
{:ok,
 <<37, 80, 68, 70, 45, 49, 46, 52, 10, 49, 32, 48, 32, 111, 98, 106, 10, 60, 60,
   10, 47, 84, 105, 116, 108, 101, 32, 40, 254, 255, 41, 10, 47, 67, 114, 101,
   97, 116, 111, 114, 32, 40, 254, 255, 0, 119, 0, 107, ...>>}
```

@vovkats you can refer my way. It could be help you.

**Comment by vovkats** [comment] 2018-04-19 16:30
@siliconavengers thank you

**Comment by gutschilla** [comment] 2018-04-24 10:33
- Alright, seemingly the real error message gets sucked up. This is an issue.
- Using Ubuntu's wkhtmltopdf is not recommended - we should point that out in the documentation

**Comment by egeersoz** [comment] 2019-03-26 18:40
Is this project still being worked on? Feels abandoned...

This error message has been giving us a lot of trouble.

**Comment by gutschilla** [comment] 2019-04-16 22:32
@egeersoz Please try again

**Comment by gutschilla** [comment] 2019-04-16 22:32
There's a new version out

**Comment by gutschilla** [comment] 2019-05-07 07:05
Since I cannot reproduce the error I'll close this. Everyone be advised to use the current (as of May 2019) binary provided by the wkhtmltopdf project. This is documented in the README file in the _prerequisites_ section. 

If this error still persists, please let me know. And yes, this library is under active development (again). I didn't have much time last in 2018 for this, unfortunately - the baby issue :baby:

**Closed by gutschilla** 2019-05-07 07:05 UTC

**Comment by gutschilla** [comment] 2019-05-07 07:07
@egeersoz - if you're still having trouble, just reopen this issue. BTW: error handling has been improved much since v0.5.0
