### ISSUE TITLE
** (FunctionClauseError) no function clause matching in System.cmd/3

### ISSUE THREAD

**Issue by shijithkjayan** [gutschilla/elixir-pdf-generator#56] opened 2019-07-09 10:28 UTC
I am working on  Elixir 1.6.6, and any pdf_generator version above 0.4.0 is throwing me this error. What might be the issue here?

`[error] #PID<0.826.0> running StarterWeb.Endpoint (cowboy_protocol) terminated
Server: localhost:4000 (http)
Request: GET /api/v1/resume/pdf/save
** (exit) an exception was raised:
    ** (FunctionClauseError) no function clause matching in System.cmd/3
        (elixir) lib/system.ex:609: System.cmd(nil, ["/var/folders/01/4lmfmjf1073c57s7gg7mxf6h0000gn/T/CV_Shijith_K_20190709.pdf", "output", "/var/folders/01/4lmfmjf1073c57s7gg7mxf6h0000gn/T/6BHzmlex.pdf", "owner_pw", "1234", "user_pw", "9Om7ymGMurtOiFsn", "encrypt_128bit", "allow", "Printing", "CopyContents"], [stderr_to_stdout: true])
        (pdf_generator) lib/pdf_generator.ex:255: PdfGenerator.encrypt_pdf/3
        (pdf_generator) lib/pdf_generator.ex:138: PdfGenerator.generate/2`

**Comment by gutschilla** [comment] 2019-07-10 14:34
Hi @shijithkjayan – looks like that for some reason `System.cmd` is being called with `nil` as first argument. Are you using wkhtmltopdf or chrome and where are your binaries installed. If you can point me to a repository, I'd be happy to dig into it.

**Comment by kiere** [comment] 2019-08-13 15:46
This is happening to me on Gigalixir (and I would imagine Heroku also).  It looks like the headless Chrome option is depending on node packages being installed globally.  It also seems to matter if you are running releases or with Mix.  We are running with releases on Gigalixir and we get this error when calling `generate_binary` (which calls `generate`).

I'm not able to think of a way to use this package with releases on Gigalixir.  wkhtmltopdf works ok, but background images render poorly and Flexbox isn't supported (but used heavily in our design).   The PDF in question renders perfectly with headless Chrome (locally, with the recommended globally-installed node packages).

There is a buildpack that may put the `google-chrome` executable where I can get to it, but if elixir-pdf-generator relies on node packages that run on top of this executable, then it's not going to work with these platforms.  I'm going to have to figure out all the options and somehow run them myself or fall back to wkhtmltopdf.

The other PDF generating alternative:
https://github.com/coletiv/puppeteer-pdf
also relies on globally installed node packages (puppeteer-pdf), so this isn't going to work on PaaS either (with releases).

I'm very interested in how people are running production Elixir systems that can deploy easily and scale if they aren't using Gigalixir or Heroku right now.  Building your own box to use global node packages seems fragile to me.

**Comment by gutschilla** [comment] 2019-08-15 15:44
@kiere I do not use Gigaliyir or Heruku but plain VMs to scale horizontally. It's a pretty simple setup. 

1.  For one client, I just spin up docker instances using https://github.com/gutschilla/elixir-pdf-server/blob/master/Dockerfile.
2. For my current employer, I use https://www.hetzner.com/cloud to spin up instances at 3EUR/month each and I rely on provisioning bash scripts (think chef) that automate box-building. Of course, this is not auto-scaling but at 3€ per month we can afford to overprovision. Also, as a cinema chain, our load is kinda capped as we can sell only so many tickets (only one ticket per seat per show)

This still doesn't help with you issue. I still didn't find an easy way to include runtime dependencies with an Elixir library to be published on hex.

**Comment by gutschilla** [comment] 2019-12-17 14:32
Adressed in https://github.com/gutschilla/elixir-pdf-generator/releases/tag/v0.6.0 - should work with Releases as well.

**Comment by gutschilla** [comment] 2019-12-17 14:33
Let me know if that fixes the issue. As we moved to Kubernetes for deployments, having simple Alpine-NodeJS images to run stuff is just very handy

**Comment by feliperenan** [comment] 2020-03-04 13:06
Hi @gutschilla 

Sorry for commenting on this closed issue, but I'm still having this issue even using the last version (0.6.0) released in my server which is an alpine linux deployed in a docker container. It works fine on my Mac OS machine though.

This is the error I'm getting on the linux server:

```
(elixir) lib/system.ex:621: System.cmd(nil, ["/opt/app/lib/pdf_generator-0.6.0/priv/node_modules/chrome-headless-render-pdf/dist/cli/chrome-headless-render-pdf.js", "--url", "file:///tmp/0wolmM04.html", "--pdf", "/tmp/0wolmM04.pdf", "--paper-width", "8.26772", "--paper-height", "11.695", "--dpi", "300"], [stderr_to_stdout: true])
```

In my case, I'm switching from `wkhtmltopdf` which was working but with some issues in the layout to `chrome-headless`. I'm sure that chromdriver, nodejs and chrome-headless-render-pdf puppeteer are being installed as well. Here a snippet from my Docker file.

```
RUN apk update && \
  apk upgrade --no-cache && \
  apk add --no-cache \
    ...
    nodejs \
    npm \
    chromium \
    chromium-chromedriver

RUN npm -g install chrome-headless-render-pdf puppeteer
```

Is there something else I need to do that I'm forgetting? 🤔 

Thanks in advance and for you awesome work in this library 💪 

cc @gutschilla

**Comment by gutschilla** [comment] 2020-03-04 13:10
Hi @feliperenan ,

Thanks for reporting. At first glance this `System.cmd(nil, [...])` looks strange. Can your please provide the call to `PdfGenerator.generate` for me to look at?

**Comment by feliperenan** [comment] 2020-03-04 13:12
here is it:

```Elixir
PdfGenerator.generate(
  html,
  generator: :chrome,
  prefer_system_executable: true,
  page_size: "A4",
  shell_params: ["--dpi", "300"],
  no_sandbox: true,
  page_size: "A4"
)
 ```

**Comment by gutschilla** [comment] 2020-03-04 13:12
@feliperenan please also provide your PdfGenerator-related config. (config.exs, prod.exs, releases.exs whatever you use)

**Comment by feliperenan** [comment] 2020-03-04 13:13
Configs:

```Elixir
config :pdf_generator,
  use_chrome: true,
  prefer_system_executable: true,
  raise_on_missing_wkhtmltopdf_binary: false
```

**Comment by gutschilla** [comment] 2020-03-04 13:16
Hmmm... let me see if I can reproduce the issue. The main thing is that System.cmd is called with nil as first param. 

...

To not spam anyone here. Would you mind opening a new issue? Are you using releases?

**Comment by gutschilla** [comment] 2020-03-04 13:17
Closed in best hopes for a new issue @feliperenan

**Closed by gutschilla** 2020-03-04 13:16 UTC
